-- 002_seed_coa.sql
-- Dashboard Monitoring Margin Proyek Divre Timur
-- Phase 1D: seed COA Tahun 2025 dari docs/COA tahun 2025.xlsx sheet SEG 5 (BIAYA).
--
-- File ini digenerate developer-time dari workbook COA, bukan fitur import Excel aplikasi.
-- Semua kode akun Seg 5 disimpan sebagai text/string, bukan numeric.

INSERT INTO coa_accounts (
  kode_seg5,
  nama,
  seg4_default,
  kategori_rab,
  tipe_fv,
  aktif
) VALUES
  ('4021', 'Upah  (Gaji + Tunj. Grade)', NULL, 'I', 'F', true),
  ('4022', 'Tunjangan (THR/Cuti/Trnsp/Rumah/UPF)', NULL, 'I', 'F', true),
  ('4023', 'Imbalan Pegawai Tetap lainnya', NULL, 'I', 'F', true),
  ('4031', 'Pengobatan / Fasilitas Kesehatan', NULL, 'I', 'F', true),
  ('4032', 'Rumah Sakit', NULL, 'I', 'V', true),
  ('4051', 'Jaminan Kecelakaan Kerja', NULL, 'I', 'F', true),
  ('4052', 'Jaminan Hari Tua', NULL, 'I', 'F', true),
  ('4053', 'Jaminan Kematian', NULL, 'I', 'F', true),
  ('4061', 'Jaminan Kesehatan', NULL, 'I', 'F', true),
  ('4071', 'Beban Lembur Pegawai', NULL, 'I', 'V', true),
  ('4081', 'Biaya Insentif / Jasa Produksi', NULL, 'I', 'V', true),
  ('4091', 'Tunjangan PPh Pasal 21', NULL, 'I', 'F', true),
  ('4101', 'Imbalan Pasca Kerja (JHT + THT)', NULL, 'I', 'F', true),
  ('4102', 'General Chek Up', NULL, 'I', 'V', true),
  ('4103', 'Biaya Penghargaan Pegawai', NULL, 'I', 'V', true),
  ('4104', 'Biaya Rekreasi Pegawai', NULL, 'I', 'V', true),
  ('4105', 'Biaya Bantuan Uang Duka', NULL, 'I', 'V', true),
  ('4106', 'Biaya Jasa Dokter & Perawat Perusahaan', NULL, 'I', 'V', true),
  ('4151', 'Upah Pegawai Proyek', NULL, 'I', 'V', true),
  ('4152', 'Tunjangan PPh 21 Proyek', NULL, 'I', 'V', true),
  ('4153', 'Tunjangan Pegawai Proyek (THR/Cuti/Trnsp/Rumah/UPF)', NULL, 'I', 'V', true),
  ('4154', 'Tenaga Kerja Lapangan', NULL, 'I', 'V', true),
  ('4155', 'Tenaga Kerja Harian/Satuan/Borongan/Oncall', NULL, 'I', 'V', true),
  ('4191', 'Pembebanan Biaya Pegawai antar Unit Kerja', NULL, 'I', 'V', true),
  ('4192', 'Pembebanan Biaya Gaji dr Kantor Pusat', NULL, 'I', 'V', true),
  ('4193', 'Sisa Anggaran ( Varabel Cost )', NULL, 'I', 'V', true),
  ('4194', 'Sisa Anggaran ( Fixed Cost )', NULL, 'I', 'V', true),
  ('4221', 'Imbalan Bukan Pegawai (Asing)', NULL, 'II', 'V', true),
  ('4231', 'Imbalan Bukan Pegawai (Lokal)', NULL, 'II', 'V', true),
  ('4241', 'Biaya Labour Supply', NULL, 'II', 'V', true),
  ('4242', 'Manajemen Fee', NULL, 'II', 'V', true),
  ('4243', 'Pembebanan Biaya LS dr Kantor Pusat', NULL, 'II', 'V', true),
  ('4301', 'Uang Saku Dinas', NULL, 'III', 'V', true),
  ('4302', 'Biaya Perjalanan Dinas', NULL, 'III', 'V', true),
  ('4303', 'Biaya Pengganti Transport', NULL, 'III', 'V', true),
  ('4411', 'Biaya Bahan', NULL, 'IV', 'V', true),
  ('4421', 'Kemitraan', NULL, 'IV', 'V', true),
  ('4422', 'Biaya Subkontraktor/ Lab Ekstern/ Konsultan', NULL, 'IV', 'V', true),
  ('4424', 'Reimbursment', NULL, 'IV', 'V', true),
  ('4431', 'Biaya Perlengkapan Kerja', NULL, 'IV', 'V', true),
  ('4432', 'Biaya Pas Pelabuhan / Bandara / Porter / Handling', NULL, 'IV', 'V', true),
  ('4435', 'Biaya Assuransi', NULL, 'IV', 'V', true),
  ('4436', 'Biaya Klaim', NULL, 'IV', 'V', true),
  ('4437', 'Honor Kegiatan Selain PT/PTT/PTT Proyek/Bukan Pegawai', NULL, 'IV', 'V', true),
  ('4438', 'Biaya Penerimaan Negara Bukan Pajak', NULL, 'IV', 'V', true),
  ('4441', 'Biaya Canvassing', NULL, 'IV', 'V', true),
  ('4451', 'Biaya Pajak Final', NULL, 'IV', 'V', true),
  ('4491', 'Biaya Operasional Intern', NULL, 'IV', 'V', true),
  ('4511', 'BiayaJasaPerawatanBangunan', NULL, 'V', 'V', true),
  ('4512', 'BiayaSewaBangunan', NULL, 'V', 'V', true),
  ('4513', 'BiayaAssuransiBangunan&Isinya', NULL, 'V', 'V', true),
  ('4514', 'BiayaHGB,IPB/KLB,PBBBangunan', NULL, 'V', 'V', true),
  ('4515', 'BiayaListrik/Air/GasBangunan', NULL, 'V', 'V', true),
  ('4516', 'BiayaMaterialBangunan', NULL, 'V', 'V', true),
  ('4521', 'BiayaJasaPerawatanPerlengkapanMesin', NULL, 'V', 'V', true),
  ('4522', 'BiayaSewaPerlengkapanMesin', NULL, 'V', 'V', true),
  ('4523', 'BiayaBBM/Pelumasdsb', NULL, 'V', 'V', true),
  ('4524', 'BiayaSukuCadangPerlengkapanMesin', NULL, 'V', 'V', true),
  ('4531', 'BiayaJasaPerawatanPeralatanOperasi', NULL, 'V', 'V', true),
  ('4532', 'BiayaAssuransiPeralatanOperasi', NULL, 'V', 'V', true),
  ('4533', 'BiayaPeralatanPenunjang', NULL, 'V', 'V', true),
  ('4534', 'BiayaBBM/Pelumasdsb', NULL, 'V', 'V', true),
  ('4535', 'BiayaSukuCadangPeralatanOperasi', NULL, 'V', 'V', true),
  ('4536', 'BiayaSewaPeralatanOperasi', NULL, 'V', 'V', true),
  ('4541', 'BiayaJasaPerawatanKendaraan', NULL, 'V', 'V', true),
  ('4542', 'BiayaSewaKendaraan', NULL, 'V', 'V', true),
  ('4543', 'BiayaAssuransiKendaraan', NULL, 'V', 'V', true),
  ('4544', 'BiayaPajakKendaraan', NULL, 'V', 'V', true),
  ('4545', 'BiayaBBM/Pelumas(Oli)dsb', NULL, 'V', 'V', true),
  ('4546', 'BiayaSukuCadangKendaraan', NULL, 'V', 'V', true),
  ('4547', 'Biaya Sewa Alat Transportasi', NULL, 'V', 'V', true),
  ('4551', 'BiayaJasaPerawatanPeralatanKantor', NULL, 'V', 'V', true),
  ('4552', 'BiayaSewaPeralatanKantor', NULL, 'V', 'V', true),
  ('4553', 'BiayaInventarisKecil', NULL, 'V', 'V', true),
  ('4561', 'BiayaJasaPerawatanPeralatanSI', NULL, 'V', 'V', true),
  ('4562', 'BiayaSewaPeralatanSI', NULL, 'V', 'V', true),
  ('4563', 'BiayaInventarisKecilSI', NULL, 'V', 'V', true),
  ('4564', 'BiayaSoftware/PerangkatLunak', NULL, 'V', 'V', true),
  ('4565', 'BiayaSukuCadangPeralatanSI', NULL, 'V', 'V', true),
  ('4566', 'BiayaLisensi', NULL, 'V', 'V', true),
  ('4591', 'Pembebanan Property Intern ( Sewa, Service & Overtime )', NULL, 'V', 'V', true),
  ('4711', 'Biaya ATK', NULL, 'VI', 'V', true),
  ('4712', 'Biaya Jasa Cetak/Fotocopy/Pelaporan', NULL, 'VI', 'V', true),
  ('4721', 'Biaya Telekomunikasi / V-Sat / Pos', NULL, 'VI', 'V', true),
  ('4722', 'Biaya Ekspedisi', NULL, 'VI', 'V', true),
  ('4731', 'Biaya Rapat', NULL, 'VI', 'V', true)
ON CONFLICT (kode_seg5) DO UPDATE SET
  nama = EXCLUDED.nama,
  seg4_default = EXCLUDED.seg4_default,
  kategori_rab = EXCLUDED.kategori_rab,
  tipe_fv = EXCLUDED.tipe_fv,
  aktif = EXCLUDED.aktif;
